import os
import sys
import time
import naoqi
from naoqi import *

# A global counter of the number of loops
count = 10

PC_IP = "192.168.0.149"  # Replace this with your computer's IP address
ROBOT_IP = "192.168.0.26" # Replace this with your NAOqi's IP address

# The name of the event generated by ALVisionRecognition
event_name = "PictureDetected"
# The name of our local python module
module_name = "python_module"

class myModule(ALModule):
    """python class myModule test auto documentation"""
    def dataChanged(self, strVarName, value, strMessage):
        """callback when data change"""
        print "datachanged", strVarName, " ", value, " ", strMessage
        global count
        count = count - 1

# Create a local broker, connected to the remote naoqi
broker = ALBroker("pythonBroker", PC_IP, 9999, ROBOT_IP, 9559)

# Create a python module
pythonModule = myModule(module_name)
try:
    # Create a proxy to ALMemory
    memoryProxy = ALProxy("ALMemory", ROBOT_IP, 9559)

    # Subscribe to the event, saying where we want to be called back
    memoryProxy.subscribeToEvent(event_name, module_name, "dataChanged")

    # Let the picture recognition run
    while count > 0:
        time.sleep(5)

    # Unsubscribe
    memoryProxy.unsubscribeToEvent(event_name, module_name)

except RuntimeError, e:
    print e
    exit(1)
print 'end'